# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore
  categories:
    - title: Bug fixes 🐛
      labels:
        - bug
        - bugs
        - fix
        - fixes
    - title: New Features 🚀
      labels:
        - feature
        - features
    - title: Dependencies updates 🛠
      labels:
        - dependencies
        - dependency
    - title: Other Changes
      labels:
        - "*"