project_name: ast-cli

release:
  draft: true
  prerelease: auto
  name_template: "AST CLI {{.Version}}"

builds:
  - main: ./cmd/main.go
    env:
      - CGO_ENABLED=0
    binary: cx
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarm: 7
      - goos: windows
        goarm: 7
    ldflags:
      - -s
      - -w
      - -X github.com/checkmarxDev/ast-cli/internal/params.Version={{.Version}}
dockers:
  - use: docker
    dockerfile: Dockerfile
    image_templates:
      - "cxsdlc/ast-cli:latest"
      - "cxsdlc/ast-cli:{{ .Tag }}"
      - "checkmarx/ast-cli:latest"
      - "checkmarx/ast-cli:{{ .Tag }}"
archives:
  - format_overrides:
      - goos: windows
        format: zip
    replacements:
      amd64: x64
      386: x32
    files:
      - LICENSE
brews:
  - tap:
      owner: checkmarx
      name: homebrew-ast-cli
      token: "{{ .Env.GO_BOT_TOKEN }}"
    folder: Formula
    homepage: https://github.com/Checkmarx/ast-cli
    description: CLI for AST
    license: Apache
    test: |
      system "#{bin}/cx version"
    install: |-
      bin.install "cx"
