# .goreleaser.yml

project_name: ast-cli

release:
  prerelease: true
  name_template: 'Checkmarx One CLI {{.Version}}'

builds:
  - main: ./cmd/main.go
    env:
      - CGO_ENABLED=0
    binary: cx-linux-amd64
    goos:
      - linux
    goarch:
      - amd64
    ignore:
      - goos: linux
        goarm: 7
    hooks:
      post: gon gonMac.hcl
    ldflags:
      - -s
      - -w
      - -X github.com/checkmarx/ast-cli/internal/params.Version={{.Version}}

  - main: ./cmd/main.go
    env:
      - CGO_ENABLED=0
    binary: cx-windows-amd64
    goos:
      - windows
    goarch:
      - amd64
    ignore:
      - goos: windows
        goarm: 7
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    hooks:
      post: gon gonMac.hcl
    ldflags:
      - -s
      - -w
      - -X github.com/checkmarx/ast-cli/internal/params.Version={{.Version}}

  - main: ./cmd/main.go
    env:
      - CGO_ENABLED=0
    binary: cx-darwin-amd64
    goos:
      - darwin
    goarch:
      - amd64
    hooks:
      post: gon gonMac.hcl
    ldflags:
      - -s
      - -w
      - -X github.com/checkmarx/ast-cli/internal/params.Version={{.Version}}

archives:
  - id: cx-linux-amd64
    builds:
      - cx-linux-amd64
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      amd64: x64
      386: x32
    files:
      - LICENSE

  - id: cx-windows-amd64
    builds:
      - cx-windows-amd64
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      amd64: x64
      386: x32
    files:
      - LICENSE

  - id: cx-darwin-amd64
    builds:
      - cx-darwin-amd64
    files:
      - LICENSE

blobs:
  - provider: s3
    region: "{{ .Env.S3_BUCKET_REGION }}"
    bucket: "{{ .Env.S3_BUCKET_NAME }}"
    folder: "CxOne/CLI/{{ .Tag }}"
    ids:
      - cx-linux-amd64
      - cx-windows-amd64
      - cx-darwin-amd64

changelog:
  use: github-native
