project_name: ast-cli

release:
  name_template: "Checkmarx One CLI {{.Version}}"

builds:
  - main: ./cmd/main.go
    env:
      - CGO_ENABLED=0
    binary: cx
    id: cx
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarm: 7
      - goos: windows
        goarm: 7
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    ldflags:
      - -s
      - -w
      - -X github.com/checkmarx/ast-cli/internal/params.Version={{.Version}}
  - main: ./cmd/main.go
    env:
      - CGO_ENABLED=0
    binary: cx
    id: cx-mac-universal
    goos:
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    ldflags:
      - -s
      - -w
      - -X github.com/checkmarx/ast-cli/internal/params.Version={{.Version}}

dockers:
  - use: docker
    dockerfile: Dockerfile
    image_templates:
      - "cxsdlc/ast-cli:latest"
      - "cxsdlc/ast-cli:{{ .Tag }}"
      - "checkmarx/ast-cli:latest"
      - "checkmarx/ast-cli:{{ .Tag }}"

archives:
  - id: cx
    builds:
      - cx
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      amd64: x64
      386: x32
    files:
      - LICENSE
  - id: cx-latest
    builds:
      - cx
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      amd64: x64
      386: x32
    files:
      - LICENSE
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
  - id: cx-mac-universal
    builds:
      - cx-mac-universal
    files:
      - LICENSE
      - ./dist/cx-mac-universal_darwin_all/cx.dmg
    name_template: "{{ .ProjectName }}_{{ .Version }}_darwin_x64"
  - id: cx-mac-universal-latest
    builds:
      - cx-mac-universal
    files:
      - LICENSE
      - ./dist/cx-mac-universal_darwin_all/cx.dmg
    name_template: "{{ .ProjectName }}_darwin_x64"

universal_binaries:
  - id: cx-mac-universal
    replace: true
    name_template: "cx"
    hooks:
      post: gon gonMac.hcl

brews:
  - tap:
      owner: checkmarx
      name: homebrew-ast-cli
      token: "{{ .Env.GO_BOT_TOKEN }}"
    folder: Formula
    homepage: https://github.com/Checkmarx/ast-cli
    description: CLI for Checkmarx One
    license: Apache
    test: |
      system "#{bin}/cx version"
    install: |-
      bin.install "cx"
      # Install bash completion
      output = Utils.popen_read("#{bin}/cx utils completion -s bash")
      (bash_completion/"cx").write output
      # Install zsh completion
      output = Utils.popen_read("#{bin}/cx utils completion -s zsh")
      (zsh_completion/"_cx").write output
      # Install fish completion
      output = Utils.popen_read("#{bin}/cx utils completion -s fish")
      (fish_completion/"cx.fish").write output

blobs:
  - provider: s3
    region: "{{ .Env.S3_BUCKET_REGION }}"
    bucket: "{{ .Env.S3_BUCKET_NAME }}"
    folder: "CxOne/CLI/{{ .Tag }}"
    ids:
      - cx
      - cx-mac-universal
  - provider: s3
    region: "{{ .Env.S3_BUCKET_REGION }}"
    bucket: "{{ .Env.S3_BUCKET_NAME }}"
    folder: "CxOne/CLI/latest"
    ids:
      - cx-latest
      - cx-mac-universal-latest

changelog:
  use: github-native