project_name: ast-cli

release:
  draft: true
  prerelease: auto
  name_template: "AST CLI {{.Version}}"

builds:
  - main: ./cmd/main.go
    env:
      - CGO_ENABLED=0
    binary: cx
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarm: 7
      - goos: windows
        goarm: 7
    ldflags:
      - -s
      - -w
      - -X github.com/checkmarx/ast-cli/internal/params.Version={{.Version}}

dockers:
  - use: docker
    dockerfile: Dockerfile
    image_templates:
      - "pedrolopesch/ast-cli:latest"
