project_name: ast-cli

release:
  draft: false
  prerelease: true
  name_template: "AST CLI Nightly"

builds:
  - main: ./cmd/main.go
    env:
      - CGO_ENABLED=0
    binary: cx
    id: cx
    goos:
      - linux
      - windows
    goarch:
      - amd64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarm: 7
      - goos: windows
        goarm: 7
    ldflags:
      - -s
      - -w
      - -X github.com/checkmarx/ast-cli/internal/params.Version={{.Version}}
      - -X main.version=nightly

  - main: ./cmd/main.go
    env:
      - CGO_ENABLED=0
    binary: cx
    id: cx-mac-arm
    goos:
      - darwin
    goarch:
      - arm64
    ldflags:
      - -s
      - -w
      - -X github.com/checkmarx/ast-cli/internal/params.Version={{.Version}}
      - -X main.version=nightly

  - main: ./cmd/main.go
    env:
      - CGO_ENABLED=0
    binary: cx
    id: cx-mac-amd
    goos:
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s
      - -w
      - -X github.com/checkmarx/ast-cli/internal/params.Version={{.Version}}
      - -X main.version=nightly

archives:
  - id: cx
    builds:
      - cx
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      amd64: x64
      386: x32
    files:
      - LICENSE
  - id: cx-mac-arm-archive
    builds:
      - cx-mac-arm
    files:
      - LICENSE
  - id: cx-mac-amd-archive
    builds:
      - cx-mac-amd
    replacements:
      amd64: x64
    files:
      - LICENSE
