project_name: ast-cli

release:
  draft: true
  prerelease: true
  name_template: "AST CLI {{.Version}}"

builds:
  - main: ./cmd/main.go
    binary: cx
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarm: 7
      - goos: windows
        goarm: 7
    ldflags:
        - -s
        - -w
        - -X github.com/checkmarxDev/ast-cli/internal/params.Version={{.Version}}

dockers:
  - image_templates:
      - "cxsdlc/ast-cli:latest"
      - "cxsdlc/ast-cli:{{ .Tag }}"
      - "gcr.io/CheckmarxDev/ast-cli:latest"
      - "gcr.io/CheckmarxDev/ast-cli:{{ .Tag }}"
    build_flag_templates:
      - "--build-arg=GIT_TOKEN={{.GITHUB_TOKEN}}"

archives:
  - format_overrides:
      - goos: windows
        format: zip
    replacements:
      amd64: x64
      386: x32
    files:
      - LICENSE
