repos:
- repo: local
  hooks: []
- repo: local
  hooks:
  - id: cx-secret-detection
    name: Cx Secret Detection
    entry: cx
    description: Run Cx CLI secret detection
    stages:
    - pre-commit
    args:
    - pre-commit
    - scan
    language: system
    pass_filenames: true
    minimum_pre_commit_version: 3.2.0
