package commands

import (
	"testing"
)

func TestAddDescriptionForIdentifiers(t *testing.T) {
	input := confidence + " 35 " + explanation + " this is a short explanation." + fix + " a fixed snippet"
	expected := "<span style=\"color: regular;\">**CONFIDENCE:**</span>" +
		"<span style=\"color: grey; font-style: italic;\"> A score between 0 (low) and 100 (high) " +
		"indicating OpenAI's confidence level for the effectiveness of the suggested remediation. <br>" +
		"</span> 35 <span style=\"color: regular;\">**EXPLANATION:**</span><span style=\"color: grey; font-style: italic;\">" +
		" An OpenAI generated description of the vulnerability. <br></span> this is a short explanation.<span style=\"color: regular;\">" +
		"**PROPOSED REMEDIATION:**</span><span style=\"color: grey; font-style: italic;\"> A customized snippet, generated by OpenAI, " +
		"that can be used to remediate the vulnerability in your code. <br></span> a fixed snippet"

	output := getActual(input, t)

	if output[len(output)-1] != expected {
		t.Errorf("Expected %q, but got %q", expected, output)
	}
}

func TestAddNewlinesIfNecessarySomeNewlines(t *testing.T) {
	input := confidence + " 35 " + explanation + " this is a short explanation.\n  " + fix + " a fixed snippet"
	expected := "<span style=\"color: regular;\">**CONFIDENCE:**</span>" +
		"<span style=\"color: grey; font-style: italic;\"> A score between 0 (low) and 100 (high) " +
		"indicating OpenAI's confidence level for the effectiveness of the suggested remediation. <br>" +
		"</span> 35 <span style=\"color: regular;\">**EXPLANATION:**</span><span style=\"color: grey; font-style: italic;\">" +
		" An OpenAI generated description of the vulnerability. <br></span> this is a short explanation.\n  <span style=\"color: regular;\">" +
		"**PROPOSED REMEDIATION:**</span><span style=\"color: grey; font-style: italic;\"> A customized snippet, generated by OpenAI, " +
		"that can be used to remediate the vulnerability in your code. <br></span> a fixed snippet"

	output := getActual(input, t)

	if output[len(output)-1] != expected {
		t.Errorf("Expected %q, but got %q", expected, output)
	}
}

func TestAddNewlinesIfNecessaryAllNewlines(t *testing.T) {
	input := confidence + " 35\n " + explanation + " this is a short explanation.\n  " + fix + " a fixed snippet"
	expected := "<span style=\"color: regular;\">**CONFIDENCE:**</span>" +
		"<span style=\"color: grey; font-style: italic;\"> A score between 0 (low) and 100 (high) " +
		"indicating OpenAI's confidence level for the effectiveness of the suggested remediation. <br>" +
		"</span> 35\n <span style=\"color: regular;\">**EXPLANATION:**</span><span style=\"color: grey; font-style: italic;\">" +
		" An OpenAI generated description of the vulnerability. <br></span> this is a short explanation.\n  <span style=\"color: regular;\">" +
		"**PROPOSED REMEDIATION:**</span><span style=\"color: grey; font-style: italic;\"> A customized snippet, generated by OpenAI, " +
		"that can be used to remediate the vulnerability in your code. <br></span> a fixed snippet"

	output := getActual(input, t)

	if output[len(output)-1] != expected {
		t.Errorf("Expected %q, but got %q", expected, output)
	}
}

func getActual(input string, t *testing.T) []string {
	someText := "some text"
	response := []string{someText, someText, input}
	output := addDescriptionForIdentifier(response)
	for i := 0; i < len(output)-1; i++ {
		if output[i] != response[i] {
			t.Errorf("All strings except last expected to stay the same")
		}
	}
	return output
}
