database:
  host: fdsfs
  port:
  name:
  username:
  password:

network:
  entrypointPort:
  entrypointTLSPort:
  privateKeyPath: priv
  certificatePath: dfsdf
  fqdn:

objectStore:
  accessKeyId:
  secretAccessKey:

messageQueue:
  username:
  password:

accessControl:
  username:
  password:

log:
  level:
  rotation:
    maxSizeMB:
    maxAgeDays: