database:
  host:
  port:
  name:
  username:
  password:

network:
  entrypointPort:
  entrypointTLSPort:
  privateKeyPath:
  certificatePath:

objectStore:
  accessKeyId:
  secretAccessKey:

messageQueue:
  username:
  password:

accessControl:
  username:
  password:

log:
  level:
  rotation:
    maxSizeMB:
    maxAgeDays: