version: 2.1 # use CircleCI 2.1
executors:
  go-container:
    docker:
      - image: circleci/golang:1.13.7
  go-lint:
    docker:
      - image: golangci/golangci-lint:v1.28.1-alpine
    resource_class: small
  circle-machine:
    machine:
      image: ubuntu-1604:202004-01
      #docker_layer_caching: true
  docker-publisher:
    environment:
      IMAGE_NAME: $DOCKER_USER/ast-cli-test
    docker:
      - image: circleci/buildpack-deps:stretch

orbs:
  checkmarx: checkmarx/circleci-kpi-shipper@0.11.0
  
jobs:
  unit-tests:
    executor: 
      circle-machine
    working_directory: ~/repo
    steps:
      - checkout
      - run: 
          name: Config GOPRIVATE environment variable
          command: echo "export GOPRIVATE=github.com/checkmarxDev/*" >> $BASH_ENV
      - run:
          name: Config Git credentials
          command: git config --global url."https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com".insteadOf "https://github.com"
      - restore_cache:
          keys:
            - go-mod-v2-{{ checksum "go.sum" }}
      - run: 
          name: go test with coverage
          command: |
            sudo chmod +x ./internal/commands/.scripts/up.sh \
            ./internal/commands/.scripts/down.sh
            sudo -E env "PATH=$PATH" go test ./... -coverprofile cover.out
          no_output_timeout: 2m
      - run:
          name: Check if total coverage is greater then 0
          command: |
          
            CODE_COV=$(go tool cover -func cover.out | grep total | awk '{print substr($3, 1, length($3)-1)}')
            EXPECTED_CODE_COV=0
            var=$(awk 'BEGIN{ print "'$CODE_COV'"<"'$EXPECTED_CODE_COV'" }')   
            if [ "$var" -eq 1 ];then
              echo "Your code coverage is too low. Coverage precentage is: $CODE_COV"
   
              exit 1
            else
              echo "Your code coverage test passed! Coverage precentage is: $CODE_COV"
              
              exit 0
            fi
      - save_cache: # Store cache in the /go/pkg directory
          key: go-mod-v2-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

  integration-tests: 
    executor: 
      circle-machine
    working_directory: ~/repo
    steps:
      - checkout
      - run: 
          name: Config GOPRIVATE environment variable
          command: echo "export GOPRIVATE=github.com/checkmarxDev/*" >> $BASH_ENV
      - run:
          name: Config Git credentials
          command: git config --global url."https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com".insteadOf "https://github.com"
      - restore_cache:
          keys:
            - go-mod-v2-{{ checksum "go.sum" }}
      - run: 
          name: go integration test          
          command: |
            sudo chmod +x ./internal/commands/.scripts/integration_up.sh            
            sudo -E env "PATH=$PATH" ./internal/commands/.scripts/integration_up.sh            
          no_output_timeout: 2m
      - save_cache: # Store cache in the /go/pkg directory
          key: go-mod-v2-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

  lint:
    executor:
      go-lint
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Config GOPRIVATE environment variable
          command: echo "export GOPRIVATE=github.com/checkmarxDev/*" >> $BASH_ENV
      - run:
          name: Config Git credentials
          command: git config --global url."https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com".insteadOf "https://github.com"
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run:
          name: Run golangci-lint
          command: golangci-lint run ./...
          no_output_timeout: 2m
      - save_cache: # Store cache in the /go/pkg directory
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
  docker-build:
    # -remove-
    executor: docker-publisher
    #executor: circle-machine
    steps:
      - checkout
      # -remove-
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build --build-arg GIT_USER=${GITHUB_USER} \
            --build-arg GIT_TOKEN=${GITHUB_TOKEN} \
            -t $IMAGE_NAME:latest .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  docker-publish-latest:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          #command: ls
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
            docker push $IMAGE_NAME:latest

  publish-github-release:
    executor:
      go-container
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          working_directory: ~/aws
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - run:
          name: Configure AWS credentials
          command: |
            aws configure set aws_access_key_id ${ACCESS_KEY_ID} --profile default
            aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY} --profile default
            aws configure set region ${AWS_REGION} --profile default
      - run:
          name: Config GOPRIVATE environment variable
          command: echo "export GOPRIVATE=github.com/checkmarxDev/*" >> $BASH_ENV
      - run:
          name: Config Git credentials
          command: git config --global url."https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com".insteadOf "https://github.com"
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run: go mod download
      - run: 
          name: Build CX CIRCLE_PROJECT_REPONAME Linux_amd64 binary 
          command: GOOS=linux GOARCH=amd64 go build -o bin/cx cmd/main.go
      - run:
          name: Build CX CLI Windows binary
          command: GOOS=windows GOARCH=amd64 go build -o bin/cx.exe cmd/main.go
      - run:
          name: Build sca-agent Linux binary
          command: GOOS=linux GOARCH=amd64 go build -o bin/cx cmd/main.go
      - run:
          name: Build MacOS binary
          command: GOOS=darwin GOARCH=amd64 go build -o bin/cx-mac cmd/main.go
      - run: go get github.com/tcnksm/ghr
      - run:
          name: Publish GitHub release
          command: |
            VERSION=$(./bin/cx version)
            VERSION="2.0.0_RC2"
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./bin/
      - save_cache: # Store cache in the /go/pkg directory
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
            
workflows:
  Visibility-workflow:
    jobs:
      - checkmarx/circleci-kpi-shipper
  Test-workflow:
    jobs:
      - unit-tests:
          filters:
            branches:
              ignore:
      - integration-tests:
          filters:
            branches:
              ignore:
      - lint:
          filters:
            branches:
              ignore:
          context: AWS
      - docker-build:
          filters:
            branches:
              ignore:
      - docker-publish-latest:
          requires:
            - docker-build
          filters:
            branches:
              only: publish-dockerhub-repo

  release-publish-workflow:
    jobs:
      - publish-github-release:
          filters:
            branches:
              only:
                - master
          context: AWS
