version: 2.1 # use CircleCI 2.1
executors:
  go-container:
    docker:
      - image: circleci/golang:1.16.6
  go-lint:
    docker:
      - image: golangci/golangci-lint:v1.40.1-alpine
    resource_class: small
  circle-machine:
    machine:
      image: ubuntu-2004:202104-01
      #docker_layer_caching: true
  docker-publisher:
    environment:
      IMAGE_NAME: ast-cli
    docker:
      - image: circleci/buildpack-deps:stretch

orbs:
  checkmarx: checkmarx/circleci-kpi-shipper@0.11.0

jobs:
  unit-tests:
    executor:
      circle-machine
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Config GOPRIVATE environment variable
          command: echo "export GOPRIVATE=github.com/checkmarxDev/*" >> $BASH_ENV
      - run:
          name: Config Git credentials
          command: git config --global url."https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com".insteadOf "https://github.com"
      - restore_cache:
          keys:
            - go-mod-v2-{{ checksum "go.sum" }}
      - run:
          name: go test with coverage
          command: |
            sudo chmod +x ./internal/commands/.scripts/up.sh \
            ./internal/commands/.scripts/down.sh
            sudo -E env "PATH=$PATH" go test ./... -coverprofile cover.out
          no_output_timeout: 2m
      - run:
          name: Check if total coverage is greater then 0
          command: |
            CODE_COV=$(go tool cover -func cover.out | grep total | awk '{print substr($3, 1, length($3)-1)}')
            EXPECTED_CODE_COV=0
            var=$(awk 'BEGIN{ print "'$CODE_COV'"<"'$EXPECTED_CODE_COV'" }')
            if [ "$var" -eq 1 ];then
              echo "Your code coverage is too low. Coverage precentage is: $CODE_COV"
              exit 1
            else
              echo "Your code coverage test passed! Coverage precentage is: $CODE_COV"
              exit 0
            fi
      - save_cache: # Store cache in the /go/pkg directory
          key: go-mod-v2-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

  integration-tests:
    executor:
      circle-machine
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Config GOPRIVATE environment variable
          command: echo "export GOPRIVATE=github.com/checkmarxDev/*" >> $BASH_ENV
      - run:
          name: Config Git credentials
          command: git config --global url."https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com".insteadOf "https://github.com"
      - restore_cache:
          keys:
            - go-mod-v2-{{ checksum "go.sum" }}
      - run:
          name: go integration test
          command: |
            sudo chmod +x ./internal/commands/.scripts/integration_up.sh
            sudo -E env "PATH=$PATH" ./internal/commands/.scripts/integration_up.sh
          no_output_timeout: 2m
      - save_cache: # Store cache in the /go/pkg directory
          key: go-mod-v2-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

  lint:
    executor:
      go-lint
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Config GOPRIVATE environment variable
          command: echo "export GOPRIVATE=github.com/checkmarxDev/*" >> $BASH_ENV
      - run:
          name: Config Git credentials
          command: git config --global url."https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com".insteadOf "https://github.com"
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run:
          name: Run golangci-lint
          command: golangci-lint run ./...
          no_output_timeout: 2m
      - save_cache: # Store cache in the /go/pkg directory
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
            
workflows:
  Visibility-workflow:
    jobs:
      - checkmarx/circleci-kpi-shipper
  Test-workflow:
    jobs:
      - unit-tests
      - integration-tests
      - lint:
          context: AWS