#!/bin/bash

wget https://sca-downloads.s3.amazonaws.com/cli/latest/ScaResolver-linux64.tar.gz
tar -xzvf ScaResolver-linux64.tar.gz
rm -rf ScaResolver-linux64.tar.gz

echo AST_INSTALLATION_PATH=$AST_INSTALLATION_PATH,AST_ROLE=$AST_ROLE,DATABASE_HOST=$DATABASE_HOST,DATABASE_PORT=$DATABASE_PORT,DATABASE_USER=$DATABASE_USER,DATABASE_PASSWORD=$DATABASE_PASSWORD,DATABASE_INSTANCE=$DATABASE_INSTANCE,ENTRYPOINT_PORT=$ENTRYPOINT_PORT,TLS_PRIVATE_KEY_PATH=$TLS_PRIVATE_KEY_PATH,TLS_CERTIFICATE_PATH=$TLS_CERTIFICATE_PATH,LOG_LEVEL=$LOG_LEVEL,LOG_LOCATION=$LOG_LOCATION,LOG_ROTATION_COUNT=$LOG_ROTATION_COUNT,LOG_ROTATION_MAX_SIZE_MB=$LOG_ROTATION_MAX_SIZE_MB,LOG_FORMAT=$LOG_FORMAT,EXTERNAL_HOSTNAME=$EXTERNAL_HOSTNAME,ELASTIC_HOST=$ELASTIC_HOST,ELASTIC_PORT=$ELASTIC_PORT,ELASTIC_INDEX=$ELASTIC_INDEX