package params

const (
	BaseURIEnv                          = "BASE_URI"
	HTTPProxyEnv                        = "HTTP_PROXY"
	ScansPathEnv                        = "SCANS_PATH"
	ProjectsPathEnv                     = "PROJECTS_PATH"
	ResultsPathEnv                      = "RESULTS_PATH"
	BflPathEnv                          = "BFL_PATH"
	SastRmPathEnv                       = "SAST_RM_PATH"
	UploadsPathEnv                      = "UPLOADS_PATH"
	CredentialsFilePathEnv              = "CREDENTIALS_FILE_PATH"
	TokenExpirySecondsEnv               = "TOKEN_EXPIRY_SECONDS"
	AccessKeyIDEnv                      = "AST_ACCESS_KEY_ID"
	AstAuthenticationPathEnv            = "AST_AUTHENTICATION_PATH"
	AccessKeySecretEnv                  = "AST_ACCESS_KEY_SECRET"
	AstRoleEnv                          = "AST_ROLE"
	AstWebAppHealthCheckPathEnv         = "AST_WEB_APP_HEALTH_CHECK_PATH"
	AstKeycloakWebAppHealthCheckPathEnv = "AST_KEYCLOAK_WEB_APP_HEALTH_CHECK_PATH"
	HealthcheckPathEnv                  = "HEALTHCHECK_PATH"
	HealthcheckDBPathEnv                = "HEALTHCHECK_DB_PATH"
	HealthcheckMessageQueuePathEnv      = "HEALTHCHECK_MESSAGE_QUEUE_PATH"
	HealthcheckObjectStorePathEnv       = "HEALTHCHECK_OBJECT_STORE_PATH"
	HealthcheckInMemoryDBPathEnv        = "HEALTHCHECK_IN_MEMORY_DB_PATH"
	HealthcheckLoggingPathEnv           = "HEALTHCHECK_LOGGING_PATH"
	HealthcheckScanFlowPathEnv          = "HEALTHCHECK_SCAN_FLOW_PATH"
	HealthcheckSastEnginesPathEnv       = "HEALTHCHECK_SAST_ENGINES_PATH"
	QueriesPathEnv                      = "QUERIES_PATH"
	QueriesCLonePathEnv                 = "QUERIES_CLONE_PATH"
	CreateOath2ClientPathEnv            = "CREATE_OATH2_CLIENT_PATH"
)
