package params

const (
	TenantEnv                           = "CX_TENANT"
	BranchEnv                           = "CX_BRANCH"
	BaseURIEnv                          = "CX_BASE_URI"
	ProxyEnv                            = "CX_HTTP_PROXY"
	ProxyTypeEnv                        = "CX_PROXY_AUTH_TYPE"
	ProxyDomainEnv                      = "CX_PROXY_NTLM_DOMAIN"
	BaseAuthURIEnv                      = "CX_BASE_AUTH_URI"
	AstUsernameEnv                      = "CX_AST_USERNAME"
	AstPasswordEnv                      = "CX_AST_PASSWORD"
	AstAPIKeyEnv                        = "CX_APIKEY"
	AccessKeyIDEnv                      = "CX_CLIENT_ID"
	AccessKeySecretEnv                  = "CX_CLIENT_SECRET"
	ScansPathEnv                        = "CX_SCANS_PATH"
	AgentNameEnv                        = "CX_AGENT_NAME"
	ProjectsPathEnv                     = "CX_PROJECTS_PATH"
	ResultsPathEnv                      = "CX_RESULTS_PATH"
	BflPathEnv                          = "CX_BFL_PATH"
	SastRmPathEnv                       = "CX_SAST_RM_PATH"
	UploadsPathEnv                      = "CX_UPLOADS_PATH"
	CredentialsFilePathEnv              = "CX_CREDENTIALS_FILE_PATH"
	TokenExpirySecondsEnv               = "CX_TOKEN_EXPIRY_SECONDS"
	AstAuthenticationPathEnv            = "CX_AST_AUTHENTICATION_PATH"
	AstRoleEnv                          = "CX_AST_ROLE"
	AstWebAppHealthCheckPathEnv         = "CX_AST_WEB_APP_HEALTH_CHECK_PATH"
	AstKeycloakWebAppHealthCheckPathEnv = "CX_AST_KEYCLOAK_WEB_APP_HEALTH_CHECK_PATH"
	HealthcheckPathEnv                  = "CX_HEALTHCHECK_PATH"
	HealthcheckDBPathEnv                = "CX_HEALTHCHECK_DB_PATH"
	HealthcheckMessageQueuePathEnv      = "CX_HEALTHCHECK_MESSAGE_QUEUE_PATH"
	HealthcheckObjectStorePathEnv       = "CX_HEALTHCHECK_OBJECT_STORE_PATH"
	HealthcheckInMemoryDBPathEnv        = "CX_HEALTHCHECK_IN_MEMORY_DB_PATH"
	HealthcheckLoggingPathEnv           = "CX_HEALTHCHECK_LOGGING_PATH"
	HealthcheckScanFlowPathEnv          = "CX_HEALTHCHECK_SCAN_FLOW_PATH"
	HealthcheckSastEnginesPathEnv       = "CX_HEALTHCHECK_SAST_ENGINES_PATH"
	QueriesPathEnv                      = "CX_QUERIES_PATH"
	QueriesCLonePathEnv                 = "CX_QUERIES_CLONE_PATH"
	CreateOath2ClientPathEnv            = "CX_CREATE_OATH2_CLIENT_PATH"
	SastScanIncPathEnv                  = "CX_SAST_SCAN_INC_PATH"
	SastScanIncMetricsPathEnv           = "CX_SAST_SCAN_INC_METRICS_PATH"
	LogsPathEnv                         = "CX_LOGS_PATH"
	LogsEngineLogPathEnv                = "CX_LOGS_ENGINE_LOG_PATH"
)
