package params

const (
	BaseURIEnv                          = "BASE_URI"
	ScansPathEnv                        = "SCANS_PATH"
	ProjectsPathEnv                     = "PROJECTS_PATH"
	ResultsPathEnv                      = "RESULTS_PATH"
	BflPathEnv                          = "BFL_PATH"
	SastRmPathEnv                       = "SAST_RM_PATH"
	UploadsPathEnv                      = "UPLOADS_PATH"
	CredentialsFilePathEnv              = "CREDENTIALS_FILE_PATH"
	TokenExpirySecondsEnv               = "TOKEN_EXPIRY_SECONDS"
	AccessKeyIDEnv                      = "AST_ACCESS_KEY_ID"
	AstAuthenticationURIEnv             = "AST_AUTHENTICATION_URI"
	AccessKeySecretEnv                  = "AST_ACCESS_KEY_SECRET"
	AstRoleEnv                          = "AST_ROLE"
	AstWebAppHealthCheckPathEnv         = "AST_WEB_APP_HEALTH_CHECK_PATH"
	AstKeycloakWebAppHealthCheckPathEnv = "AST_KEYCLOAK_WEB_APP_HEALTH_CHECK_PATH"
	HealthcheckPathEnv                  = "HEALTHCHECK_PATH"
	HealthcheckDBPathEnv                = "HEALTHCHECK_DB_PATH"
	HealthcheckMessageQueuePathEnv      = "HEALTHCHECK_MESSAGE_QUEUE_PATH"
	HealthcheckObjectStorePathEnv       = "HEALTHCHECK_OBJECT_STORE_PATH"
	HealthcheckInMemoryDBPathEnv        = "HEALTHCHECK_IN_MEMORY_DB_PATH"
	HealthcheckLoggingPathEnv           = "HEALTHCHECK_LOGGING_PATH"
	HealthcheckGetAstRolePathEnv        = "HEALTHCHECK_GET_AST_ROLE_PATH"
	ScanHealthCheckSourcePathEnv        = "SCAN_HEALTHCHECK_SOURCE_PATH"
)
