name: AI Code Review

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  code_review:
    uses: Checkmarx/plugins-release-workflow/.github/workflows/ai-code-review.yml@main
    with:
      open_ai_model: "gpt-4-1106-preview"
      exclude_pattern: ""
    secrets: inherit
