name: Dependabot auto-merge
on: pull_request

permissions:
  contents: write

jobs:
  dependabot-merge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.3.1
        with:
          github-token: "${{ secrets.GH_TOKEN }}"
      - name: Enable auto-merge for Dependabot PRs
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
        run: gh pr merge --auto --merge "$PR_URL"
      - name: Auto approve dependabot PRs
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
