name: Docker Image Scan

on:
  pull_request:

permissions:
  contents: read

jobs:
  checkDockerImage:
    runs-on: cx-public-ubuntu-x64
    name: Scan Docker Image with Trivy
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v6
        with:
          persist-credentials: false
      - name: Build the project
        run: go build -o ./cx ./cmd
      - name: Build Docker image
        run: docker build -t ast-cli:${{ github.sha }} .
      - name: Run Trivy scanner without downloading DBs
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 #v0.35.0
        with:
          scan-type: 'image'
          image-ref: ast-cli:${{ github.sha }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          output: './trivy-image-results.txt'
        env:
          TRIVY_SKIP_JAVA_DB_UPDATE: true

      - name: Inspect action report
        if: always()
        shell: bash
        run: cat ./trivy-image-results.txt
