name: AST Cli integration test

on:
  push:
  workflow_dispatch:
    inputs:
      baseUri:
        description: 'Cx Base URI'
        required: true
      baseAuthUri:
        description: 'Cx Base Auth URI'
        required: true
      apiKey:
        description: 'Cx API Key'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: "github.com/checkmarxDev/*"
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.2'
      - name: Setup git
        run: git config --global url."https://${{ secrets.PERSONAL_ACCESS_TOKEN }}:@github.com/".insteadOf "https://github.com"
      - name: Download
        run: go build -o ./bin/cx ./cmd
      - name: Go Integration test
        env:
          CX_BASE_URI: ${{ github.event.inputs.baseUri }}
          CX_BASE_AUTH_URI: ${{ github.event.inputs.baseAuthUri }}
          CX_APIKEY: ${{ github.event.inputs.apiKey }}
        run: go test ./test/integration/scan_test.go