name: AST Cli integration test

on:
  workflow_dispatch:
    inputs:
      baseUri:
        description: 'AST Base URI'
        required: true
      baseAuthUri:
        description: 'AST Base Auth URI'
        required: true
      secret_token:
        description: 'AST API Key'
        required: true
      tenant:
        description: 'Tenant'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: "github.com/checkmarxDev/*"
    steps:
      - name: Masking inputs
        id: add_masks
        run: |
          INP_SECRET_TOKEN=$(jq -r '.inputs.secret_token' $GITHUB_EVENT_PATH)
          echo ::add-mask::$INP_SECRET_TOKEN
          echo CX_APIKEY="$INP_SECRET_TOKEN" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.2'
      - name: Setup git
        run: git config --global url."https://${{ secrets.PERSONAL_ACCESS_TOKEN }}:@github.com/".insteadOf "https://github.com"
      - name: Download
        run: go build -o ./bin/cx ./cmd
      - name: Go Integration test
        shell: bash
        env:
          CX_BASE_URI: ${{ github.event.inputs.baseUri }}
          CX_BASE_AUTH_URI: ${{ github.event.inputs.baseAuthUri }}
          CX_AST_USERNAME: ${{ github.event.inputs.username }}
          CX_TENANT: ${{ github.event.inputs.tenant }}
        run: |
          sudo chmod +x ./internal/commands/.scripts/integration_up.sh
          ./internal/commands/.scripts/integration_up.sh