name: Manual Tag Creation

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Next release tag'
        required: true

jobs:
  tag-creation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Tag
        run: |
          echo ${{ github.event.inputs.tag }}
          echo "NEXT_VERSION=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
      - name: Create tag
        uses: actions-ecosystem/action-push-tag@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          tag: ${{ env.NEXT_VERSION }}
