name: Manual Tag Creation

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Next release tag'
        required: true

jobs:
  tag-creation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Tag
        run: |
          echo ${{ github.event.inputs.tag }}
          echo "NEXT_VERSION=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          tag=${{ github.event.inputs.tag }}
          message='${{ github.event.inputs.tag }}: PR #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}'
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git tag -a "${tag}" -m "${message}"
          git push origin "${tag}"
