name: Nightly Release

permissions:
  id-token: write
  contents: write

on:
  push:
    branches:
      - main

jobs:
  delete_tag:
    uses: Checkmarx/ast-cli/.github/workflows/delete-dev-releases.yml@main
    with:
      tag: "2.0.0-nightly"
    secrets: inherit
  nightly:
    needs: delete_tag
    uses: Checkmarx/ast-cli/.github/workflows/release.yml@main
    with:
      tag: "2.0.0-nightly"
    secrets: inherit
