name: PR Automation
on:
  pull_request_target:
    types: [ready_for_review, opened, reopened]

permissions:
  contents: none
  issues: write
  pull-requests: write

jobs:
  add-assignee-and-reviewers:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.type != 'Bot' }}
    steps:
      - name: Request reviewers
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          PRNUM: ${{ github.event.pull_request.number }}
          PRAUTHOR: ${{ github.event.pull_request.user.login }}
        run: gh pr edit $PRNUM --add-reviewer Checkmarx/ast-galactica-team
