name: AST Cli Release

on:
  workflow_call:
    inputs:
      tag:
        description: 'Next release tag'
        required: true
        type: string
      dev:
        description: 'Is dev build'
        required: false
        default: true
        type: boolean
  workflow_dispatch:
    inputs:
      tag:
        description: 'Next release tag'
        required: true
        type: string
      dev:
        description: 'Is dev build'
        required: false
        default: true
        type: boolean

permissions:
  id-token: write
  contents: write

jobs:

  notify:

    uses: Checkmarx/plugins-release-workflow/.github/workflows/release-notify.yml@main
    with:
      product_name: CLI
      release_version: ${{ inputs.tag }}
      cli_release_version: ""
      release_author: "Phoenix Team"
      release_url: https://github.com/Checkmarx/ast-cli/releases/tag/${{ inputs.tag }}
    secrets: inherit
