name: AST Cli Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: macos-latest
    env:
      AC_PASSWORD: ${{ secrets.AC_PASSWORD }}
      APPLE_DEVELOPER_CERTIFICATE_P12_BASE64: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_P12_BASE64 }}
      APPLE_DEVELOPER_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.17.1'
      - name: Import Code-Signing Certificates
        uses: Apple-Actions/import-codesign-certs@v1
        with:
          # The certificates in a PKCS12 file encoded as a base64 string
          p12-file-base64: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_P12_BASE64 }}
          # The password used to import the PKCS12 file.
          p12-password: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_PASSWORD }}
      - name: Updating and upgrading brew
        run: |
          ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
          brew --version
      - name: Install gon
        run: |
          brew tap mitchellh/gon
          brew install mitchellh/gon/gon
      - name: Install and start docker
        run: |
          brew install --cask docker
          sudo /Applications/Docker.app/Contents/MacOS/Docker --unattended --install-privileged-components
          open -a /Applications/Docker.app --args --unattended --accept-license
          while ! /Applications/Docker.app/Contents/Resources/bin/docker info &>/dev/null; do sleep 1; done
      - name: Test docker
        run: |
          docker version
          docker info
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Clean
        run: |
          rm default.profraw
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2.6.1
        with:
          version: v0.179.0
          args: release --rm-dist --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GO_BOT_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Teams notification
          uses: toko-bifrost/ms-teams-deploy-card@master
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            webhook-uri: ${{ secrets.TEAMS_WEBHOOK_URI }}
            custom-facts: |
              - name: Release :
                #value: ${{ steps.latest_release.outputs.html_url }}
                value: "link to release or notes, harcoded because i did not considered go releaser ... maybe in this metadata variable from output"
            custom-actions: |
              - name: View CI Logs
                value: https://github.com/Checkmarx/ast-cli/actions/runs/${{ github.run_id }}"
              - name: View HEAD Commit
                value: https://github.com/Checkmarx/ast-cli/commit/${{ github.sha }}