name: AST Cli Release

on:
  workflow_call:
    inputs:
      tag:
        description: 'Next release tag'
        required: true
        type: string
      dev:
        description: 'Is dev build'
        required: false
        default: true
        type: boolean
  workflow_dispatch:
    inputs:
      tag:
        description: 'Next release tag'
        required: true
        type: string
      dev:
        description: 'Is dev build'
        required: false
        default: true
        type: boolean

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: macos-latest
    env:
      AC_PASSWORD: ${{ secrets.AC_PASSWORD }}
      APPLE_DEVELOPER_CERTIFICATE_P12_BASE64: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_P12_BASE64 }}
      APPLE_DEVELOPER_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_PASSWORD }}
      PRIVATE_KEY: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCrsovoXIXsMtgE
        KGbCH+6K9xtoD4Yy6aGmHjs+32ziIcpplPXkvI/wvIU7D1bmCNlS/2H1R/F0VYKk
        bZWZ//3xqBKANS4wGqTrSC++/0HIDrE93EpENREdPFDwKavwVdqj5PdxnUWYjPhI
        7qdtM+O8ZELymjEDDhVcDNo8K5au5eWP/xYLHE+lRpLhzfzQd79G+xG+hqgn+Lnt
        Lywh+Vksy+rQ0Z+CvjwFCQbDut0MHJYXxrO6nAMChmKO3GXmvOb18BAEWnhXjCFb
        7VgC8JoNUyNtjBxia/hAKVFMjYx4LfiKzIcxzhkoJ8BMaNyjh+EL5hFCb9P+J601
        mJWuy7xxAgMBAAECggEAAPa6PBJL4qbo6UIQTJnpCQDo15lRtaaz1HbCOqC+r9jE
        dfoC9NcdoDpwrYORJ26oiKOcGUg/edmSh4mBb9k8486/ltZllVnK7/KqaPIuHHk/
        o7MhPBeHqnA4nJaBS3Kx7N5XyLybI8dzy9YCHNXwGvI9oXa93HBnbIo6beDJQl9P
        42SQduHAcAVEKJ+J+gk6rnM5qtCtmCBGRFzSlD2/GT1wNGvYju8+Hdj8camOpzki
        ZBVsw+ZFZVYQqYTiUe0xMy6oMrT2rtbDV+Plp+iRLBP4e5u7B42HPgf/6bzZOaWC
        IiUb5cQW+0Aw4YTb/5mNRgITf6ZfcpvDBrFBY+PhgQKBgQDSiS9nunbi1wlH77ym
        69KeHy7HBt42LyFPmsWEr4SQS2/ujoPnrZL9yiiEJ8CCvrXFDLg4YZFxA99vlCI0
        yHfGwZSq5bMCJzT04pl3XMDkvTQGvX9eupjehXHc2y4GlH2iDKJwbx9wzYiKwOFG
        ghcHGfAZLrOv4OGvLMUjBnuNwQKBgQDQxkz0B0DoZbbcjNo0LWVkLxUxB0VYGXcy
        NR9+3gFg8P27Hf6/uiryULncA8Bf2Sl/u8Q2wES7f9qIcyu70aB1zJheV7EFEgUb
        JN7vqLpO1FP1DdiglDZoPIFjZwOEgEZ0e7vvWxc3eFaSNo0N8Fh/FwjXIENsaazj
        4i6jh4E6sQKBgHEcdzWZfon80eWuLYLYq/1771vKmtQtmg30ry3MRsJnZSmbs85i
        +NgVJpNp8AnOgEXvwYG5GbTISeDei0okcgV8t2zhn70GZ3Mx0xXH5XJ/HFaKtMWm
        Jr9Wnofz0dSDLsRDWXpimVe3dSZm3iFNfyW3j8FXz/4sKdQ9j2Rz9SmBAoGAUEiR
        ex329ed3ZGS93GbAoMACVDJJllFkpugKzoys1wyVZglo123N6hTlBBhlN/aYoMgh
        8jQJuli2PtabMMSyAdrFlTH/nsWJNSD+ogaubnX0Oz4x2b5lFbx+vSz2C1QQw+Z5
        JNhQm0IpeFyF7aBJR8Yh3ihIBT61/4QRD02igmECgYEAlKHDjiFB1dcM+Ac456hS
        /UV2As3ZxVaP7qzU63ESk8Gpl9U1zwsVyLOa3/wquYvZ9lTtpLk1LO22EhepgFRv
        59mt1cjlYB+tJ9gh2MYvTA4vh8ooebgS+k5muII3eoo646gtbWtth5ohqIQh5u3b
        OCt3xtlfdxPkal6M3L09ovw=
        -----END RSA PRIVATE KEY-----
      PUBLIC_KEY: |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAq7KL6FyF7DLYBChmwh/u
        ivcbaA+GMumhph47Pt9s4iHKaZT15LyP8LyFOw9W5gjZUv9h9UfxdFWCpG2Vmf/9
        8agSgDUuMBqk60gvvv9ByA6xPdxKRDURHTxQ8Cmr8FXao+T3cZ1FmIz4SO6nbTPj
        vGRC8poxAw4VXAzaPCuWruXlj/8WCxxPpUaS4c380He/RvsRvoaoJ/i57S8sIflZ
        LMvq0NGfgr48BQkGw7rdDByWF8azupwDAoZijtxl5rzm9fAQBFp4V4whW+1YAvCa
        DVMjbYwcYmv4QClRTI2MeC34isyHMc4ZKCfATGjco4fhC+YRQm/T/ietNZiVrsu8
        cQIDAQAB
        -----END PUBLIC KEY-----
      EXE_PATH: ./dist/cx-win/cx.exe
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Import Code-Signing Certificates
        uses: Apple-Actions/import-codesign-certs@253ddeeac23f2bdad1646faac5c8c2832e800071 #v1
        with:
          # The certificates in a PKCS12 file encoded as a base64 string
          p12-file-base64: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_P12_BASE64 }}
          # The password used to import the PKCS12 file.
          p12-password: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_PASSWORD }}
      - name: Updating and upgrading brew
        run: |
          git config --global pack.windowMemory "100m"
          git config --global pack.SizeLimit "100m" 
          git config --global pack.threads "1"
          git config --global pack.window "0"
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew --version
      - name: Install gon
        run: |
          brew install Bearer/tap/gon
      - name: Install and start docker
        if: inputs.dev == false
        run: |
          brew install docker
          colima start
          sudo ln -sf $HOME/.colima/default/docker.sock /var/run/docker.sock
      - name: Test docker
        if: inputs.dev == false
        run: |
          docker version
          docker info
      - name: Login to Docker Hub
        if: inputs.dev == false
        uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7 #v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@5fd3084fc36e372ff1fff382a39b10d03659f355 #v2
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_ASSUME_ROLE_REGION }}
      - name: Tag
        run: |
          echo ${{ inputs.tag }}
          echo "NEXT_VERSION=${{ inputs.tag }}" >> $GITHUB_ENV
          tag=${{ inputs.tag }}
          message='${{ inputs.tag }}: PR #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}'
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git tag -a "${tag}" -m "${message}"
          git push origin "${tag}"
      - name: Build GoReleaser Args
        run: |
          args='release --clean --debug'
          if [ ${{ inputs.dev }} = true ]; then
            args=${args}' --config=".goreleaser-dev.yml"'
          fi
          echo "GR_ARGS=${args}" >> $GITHUB_ENV
      - name: Install OpenSSL
        run: brew install openssl
      - name: Sign Windows Executable
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          openssl dgst -sha256 -sign private_key.pem -out "$EXE_PATH.sig" "$EXE_PATH"
          rm private_key.pem
      - name: Echo GoReleaser Args
        run: echo ${{ env.GR_ARGS }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@b508e2e3ef3b19d4e4146d4f8fb3ba9db644a757 #v3
        with:
          version: v1.18.2
          args: ${{ env.GR_ARGS }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GO_BOT_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          S3_BUCKET_REGION: ${{ secrets.S3_BUCKET_REGION }}

  notify:
    runs-on: ubuntu-latest
    if: inputs.dev == false
    needs: build
    steps:
      - name: Get latest release notes
        id: release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          body_release="$(gh api -H "Accept: application/vnd.github.v3+json" /repos/Checkmarx/ast-cli/releases/latest | jq -r '.body' )"
          body_release="${body_release//$'\n'/'%0A'}"
          echo "::set-output name=body_release::$body_release"

      - name: Converts Markdown to HTML
        id: convert
        uses: lifepal/markdown-to-html@71ed74a56602597c05dd7dd0e561631557158ed5 #v1.1
        with:
          text: "${{ steps.release.outputs.body_release }}"

      - name: Clean html
        id: clean
        run: |
          clean="$(echo "${{ steps.convert.outputs.html }}" | awk '{gsub(/id=.[a-z]+/,"");print}' | tr -d '\n')"
          echo "$clean"
          echo "::set-output name=clean::$clean"

      - name: Send a Notification
        id: notify
        uses: thechetantalwar/teams-notify@8a78811f5e8f58cdd204efebd79158006428c46b #v2
        with:
          teams_webhook_url: ${{ secrets.TEAMS_WEBHOOK_URI }}
          message: "${{ steps.clean.outputs.clean }}"
